ALLOWED_SPECIAL_CHARS = "!@#$%^&*()-_=+[]{}|;:<>?"

NAMED_CHAR_TO_CHAR = {
    "period": ".",
    "dot": ".",
    "comma": ",",
    "tilde": "~",
    "space": " ",
    "whitespace": " ",
    "dash": "-",
    "hyphen": "-",
    "underscore": "_",
    "colon": ":",
    "semicolon": ";",
    "quote": "'",
    "double quote": '"',
    "apostrophe": "'",
    "slash": "/",
    "backslash": "\\",
    "pipe": "|",
    "plus": "+",
    "minus": "-",
    "equals": "=",
    "equal": "=",
    "question mark": "?",
    "exclamation": "!",
    "exclamation mark": "!",
    "bang": "!",
    "caret": "^",
    "percent": "%",
    "ampersand": "&",
    "at": "@",
    "hash": "#",
    "pound": "#",
    "dollar": "$",
    "asterisk": "*",
    "star": "*",
    "parenthesis": "()",
    "bracket": "[]",
    "brace": "{}",
    "angle bracket": "<>",
    "less than": "<",
    "greater than": ">",
}


